#pragma once
#ifndef BLOBTREESCRIPTING_H
#define BLOBTREESCRIPTING_H

namespace PS{
	namespace BLOBTREE{

typedef const char* PSToken;

PSToken PS_UNION		= "UNION";
PSToken PS_INTERSECTION = "INTERSECTION";
PSToken PS_DIFFERENCE	= "DIFFERENCE";
PSToken PS_SMOOTHDIF	= "SMOOTH DIFFERENCE";
PSToken PS_BLEND		= "BLEND";
PSToken PS_RICCIBLEND	= "RICCI BLEND";
PSToken PS_AFFINE		= "AFFINE";
PSToken PS_WARPTWIST	= "TWIST";
PSToken PS_WARPTAPER	= "TAPER";
PSToken PS_WARPBEND		= "BEND";
PSToken PS_WARPSHEAR	= "SHEAR";
PSToken PS_CACHE		= "CACHE";
PSToken PS_TEXTURE		= "TEXTURE";
PSToken PS_PCM			= "PCM";

PSToken PS_LINE			= "LINE";
PSToken PS_POINT		= "POINT";
PSToken PS_CYLINDER		= "CYLINDER";
PSToken PS_DISC			= "DISC";
PSToken PS_RING			= "RING";
PSToken PS_POLYGON		= "POLYGON";
PSToken PS_CUBE			= "CUBE";
PSToken PS_TRIANGLE		= "TRIANGLE";
PSToken PS_CATMULLROMCURVE	= "CATMULLROMCURVE";

	}
}
#endif